[package]
name = "etf"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"]}
date_time_parser = "0.2.0"
git2 = "0.20.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_yml = "0.0.12"
